services:
  pix-verifier:
    image: filipebezerrasantos/pix-verifier:v2.0.0-rc
    hostname: pix-verifier
    container_name: pix-verifier
    restart: unless-stopped
    environment:
      - TZ=America/Fortaleza
      - DB_HOST=postgres
      - DB_NAME=pixverifier
      - DB_USER=dbadmin
      - DB_PASS=f|Vyi2LjVG8DO7%2)Tz>9PfA&F[2]jQ6
    volumes:
      - pixverifier_certs:/var/www/services/certs
    ports:
      - "80:80"
    networks:
      - pixverifier_network
    depends_on:
      postgres:
        condition: service_healthy 

  postgres:
    container_name: postgres
    image: postgres:16-alpine3.19
    hostname: postgres16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./conf/sql:/docker-entrypoint-initdb.d
    environment:
      - TZ=America/Fortaleza
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=f|Vyi2LjVG8DO7%2)Tz>9PfA&F[2]jQ6
    ports:
      - "5432:5432"
    networks:
      - pixverifier_network
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U dbadmin"]
          interval: 5s
          retries: 5
          start_period: 10s

volumes:
  postgres_data:
    name: postgres_data
  pixverifier_certs:
    name: pixverifier_certs

networks:
  pixverifier_network:
    name: pixverifier_network
